#ifndef _CTC_ERROR_H_
#define _CTC_ERROR_H_

enum ctc_error_code
{
    /* API error */
    CTC_FAILED                                = -1,
    CTC_FAILED_INVALID_ARGS                   = -2,
    CTC_FAILED_INVALID_CONNECTION_STRING      = -3,
    CTC_FAILED_ALLOC_CTC_HANDLE               = -4,
    CTC_FAILED_FREE_CTC_HANDLE                = -5,
    CTC_FAILED_INVALID_CTC_HANDLE             = -6,
    CTC_FAILED_ALLOC_JOB_DESC                 = -7,
    CTC_FAILED_FREE_JOB_DESC                  = -8,
    CTC_FAILED_INVALID_JOB_DESC               = -9,
    CTC_FAILED_EXCEED_RAW_DATA_BUFFER_COUNT   = -10,
    CTC_FAILED_EXCEED_JSON_ARRAY_SIZE         = -11,
    CTC_FAILED_CONVERT_TO_JSON_FORMAT         = -12,
    CTC_FAILED_JANSSON_EXTERNAL_LIBRARY       = -13,
    CTC_FAILED_TOO_SMALL_RESULT_BUFFER_SIZE   = -14,

    /* network error */
    CTC_FAILED_OPEN_CONTROL_SESSION           = -100,
    CTC_FAILED_CLOSE_CONTROL_SESSION          = -101,
    CTC_FAILED_COMMUNICATE_CONTROL_SESSION    = -102,
    CTC_FAILED_OPEN_JOB_SESSION               = -103, 
    CTC_FAILED_CLOSE_JOB_SESSION              = -104,
    CTC_FAILED_COMMUNICATE_JOB_SESSION        = -105,
    CTC_FAILED_POLL_TIMEOUT                   = -106,
    CTC_FAILED_OVERFLOW_DATA_PAYLOAD_MAX_SIZE = -107,

    /* received protocol error */
    CTC_FAILED_RECEIVE_INVALID_OP_ID          = -200,
    CTC_FAILED_RECEIVE_INVALID_RESULT_CODE    = -201,
    CTC_FAILED_RECEIVE_INVALID_JOB_DESC       = -202,
    CTC_FAILED_RECEIVE_INVALID_SESSION_GID    = -203,
    CTC_FAILED_RECEIVE_NOT_SUPPORTED_PROTOCOL = -204,
    CTC_FAILED_RECEIVE_INVALID_STATUS         = -205,
    CTC_FAILED_RECEIVE_INVALID_DATA_PAYLOAD   = -206,

    /* job thread error */
    CTC_FAILED_CREATE_JOB_THREAD              = -300,
    CTC_FAILED_DESTROY_JOB_THREAD             = -301,

    /* server error */
    CTC_SERVER_FAILED_UNKNOWN_ERROR                = -500,
    CTC_SERVER_FAILED_WRONG_PACKET                 = -501,
    CTC_SERVER_FAILED_UNKNOWN_OPERATION            = -502,
    CTC_SERVER_FAILED_OUT_OF_RANGE                 = -503,
    CTC_SERVER_FAILED_INVALID_HANDLE               = -504,
    CTC_SERVER_FAILED_INSUFFICIENT_SERVER_RESOURCE = -505,
    CTC_SERVER_FAILED_CREATE_SESSION               = -506,
    CTC_SERVER_FAILED_SESSION_NOT_EXIST            = -507,
    CTC_SERVER_FAILED_SESSION_IS_BUSY              = -508,
    CTC_SERVER_FAILED_SESSION_CLOSE                = -509,
    CTC_SERVER_FAILED_NO_MORE_JOB_ALLOWED          = -510,
    CTC_SERVER_FAILED_INVALID_JOB                  = -511,
    CTC_SERVER_FAILED_INVALID_JOB_STATUS           = -512,
    CTC_SERVER_FAILED_INVALID_TABLE_NAME           = -513,
    CTC_SERVER_FAILED_TABLE_ALREADY_EXIST          = -514,
    CTC_SERVER_FAILED_UNREGISTERED_TABLE           = -515,
    CTC_SERVER_FAILED_JOB_ATTR_NOT_EXIST           = -516,
    CTC_SERVER_FAILED_INVALID_JOB_ATTR_VALUE       = -517,
    CTC_SERVER_FAILED_NOT_SUPPORTED_FILTER         = -518,
    CTC_SERVER_FAILED_JOB_ALREADY_STARTED          = -519,
    CTC_SERVER_FAILED_JOB_ALREADY_STOPPED          = -520
};

#endif
